package ec.uce.propuestas.cronograma;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import ec.uce.propuestas.cronograma.entity.Cronograma;
import ec.uce.propuestas.cronograma.repository.CronogramaRepository;
import ec.uce.propuestas.presupuesto.entity.Presupuesto;
import ec.uce.propuestas.presupuesto.repository.PresupuestoRepository;
import ec.uce.propuestas.proyecto.entity.Proyecto;
import ec.uce.propuestas.proyecto.repository.ProyectoRepository;
import ec.uce.propuestas.usuario.Rol;
import ec.uce.propuestas.usuario.Usuario;
import ec.uce.propuestas.usuario.UsuarioRepository;
import io.quarkus.test.TestTransaction;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.regex.Pattern;
import javax.sql.DataSource;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Plan 027 — focused invariants for the {@code cronograma} JPA entity and
 * repository:
 *
 * <ul>
 *   <li>{@code publicId} UUIDv7 generated by the column {@code public_id}
 *       (insertable=false, updatable=false, {@code @Generated(INSERT)}).</li>
 *   <li>FK {@code presupuestoId} is {@code Long} (BIGINT).</li>
 *   <li>Owner-scoped resolution returns empty for foreign callers.</li>
 *   <li>Hibernate-level mutation of {@code publicId} is rejected
 *       (updatable=false).</li>
 * </ul>
 */
@QuarkusTest
class CronogramaJpaIT {

    private static final Pattern UUID_V7 =
            Pattern.compile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$");

    @Inject
    DataSource dataSource;

    @Inject
    EntityManager entityManager;

    @Inject
    UsuarioRepository usuarioRepository;

    @Inject
    ProyectoRepository proyectoRepository;

    @Inject
    PresupuestoRepository presupuestoRepository;

    @Inject
    CronogramaRepository cronogramaRepository;

    @BeforeEach
    void reset() throws Exception {
        try (java.sql.Connection connection = dataSource.getConnection();
                java.sql.Statement statement = connection.createStatement()) {
            statement.execute("TRUNCATE TABLE cronograma, actividad, apu_detalle, apu_seccion, apu, "
                    + "rubro, capitulo, presupuesto, insumo, base_insumos, "
                    + "parametros_proyecto, firmante, proyecto, token_usuario, refresh_token, usuario "
                    + "RESTART IDENTITY CASCADE");
        }
    }

    @Test
    void cronograma_entity_declares_uuid_public_id_with_generated_immutable_mapping() throws Exception {
        Field publicIdField = lookupField(Cronograma.class, "publicId");
        assertNotNull(publicIdField, "Cronograma must declare publicId field");
        assertEquals(UUID.class, publicIdField.getType(), "Cronograma.publicId must be UUID");

        Generated generated = publicIdField.getAnnotation(Generated.class);
        assertNotNull(generated, "Cronograma.publicId must carry @Generated");
        assertEquals(
                List.of(EventType.INSERT),
                List.of(generated.event()),
                "Cronograma.publicId @Generated.event must be INSERT");

        jakarta.persistence.Column column = publicIdField.getAnnotation(jakarta.persistence.Column.class);
        assertNotNull(column, "Cronograma.publicId must carry @Column");
        assertFalse(column.insertable(), "Cronograma.publicId must be insertable=false");
        assertFalse(column.updatable(), "Cronograma.publicId must be updatable=false");
        assertEquals("public_id", column.name(), "Cronograma.publicId must map to public_id");

        // FK remains BIGINT Long (NOT UUID)
        Field presupuestoIdField = lookupField(Cronograma.class, "presupuestoId");
        assertNotNull(presupuestoIdField, "Cronograma must declare presupuestoId");
        assertEquals(
                Long.class,
                presupuestoIdField.getType(),
                "Cronograma.presupuestoId must remain Long (BIGINT) — internal FK only");
    }

    @Test
    @TestTransaction
    void cronograma_publicId_is_generated_as_uuidv7_after_persist() {
        Seed seed = seedParentGraph();
        Cronograma cronograma = new Cronograma();
        cronograma.presupuestoId = seed.presupuestoId;
        cronograma.unidadTiempo = "SEMANA";
        cronograma.numeroPeriodos = 12;
        cronograma.totalGeneralRevisado = null;
        cronograma.fechaRevision = null;
        cronograma.presupuestoFingerprintRevisado = null;
        cronogramaRepository.persist(cronograma);

        assertNotNull(cronograma.publicId, "Cronograma.publicId must be populated after persist");
        assertTrue(
                UUID_V7.matcher(cronograma.publicId.toString()).matches(),
                "Cronograma.publicId must be a UUIDv7: " + cronograma.publicId);
        assertEquals(7, cronograma.publicId.version(), "Cronograma UUIDv7 version nibble must be 7");
        assertEquals(2, cronograma.publicId.variant(), "Cronograma UUIDv7 must use RFC 4122 variant");
    }

    @Test
    @TestTransaction
    void cronograma_orm_immutability_blocks_public_id_mutation() {
        Seed seed = seedParentGraph();
        Cronograma cronograma = new Cronograma();
        cronograma.presupuestoId = seed.presupuestoId;
        cronograma.unidadTiempo = "SEMANA";
        cronograma.numeroPeriodos = 12;
        cronogramaRepository.persist(cronograma);

        UUID original = cronograma.publicId;
        UUID pretend = UUID.fromString("0192f6c4-7c8a-7abc-8def-feedfacedead");

        entityManager.clear();
        Cronograma reloaded = cronogramaRepository.findById(cronograma.id);
        assertNotNull(reloaded);
        reloaded.publicId = pretend;
        cronogramaRepository.persist(reloaded);

        entityManager.clear();
        Cronograma reread = cronogramaRepository.findById(cronograma.id);
        assertEquals(
                original, reread.publicId, "Cronograma.publicId must NOT be mutable through the ORM (updatable=false)");
    }

    @Test
    @TestTransaction
    void cronograma_owner_scope_returns_row_for_owner_and_hides_from_foreign() {
        Seed seed = seedParentGraph();
        Usuario foreign = persistUsuario("foreign-crono@ex.com");
        Cronograma cronograma = persistCronograma(seed.presupuestoId);

        Optional<Cronograma> ownerResolved =
                cronogramaRepository.findByPublicIdAndOwnerScope(cronograma.publicId, seed.ownerId);
        assertTrue(ownerResolved.isPresent(), "owner must resolve their own cronograma by publicId");
        assertEquals(cronograma.id, ownerResolved.get().id);

        Optional<Cronograma> foreignResolved =
                cronogramaRepository.findByPublicIdAndOwnerScope(cronograma.publicId, foreign.id);
        assertTrue(foreignResolved.isEmpty(), "foreign owner must NOT see another user's cronograma (404 semantics)");

        UUID invented = UUID.fromString("0192f6c4-7c8a-7000-8000-000000000000");
        Optional<Cronograma> inventedResolved =
                cronogramaRepository.findByPublicIdAndOwnerScope(invented, seed.ownerId);
        assertTrue(inventedResolved.isEmpty(), "An invented UUIDv7 must not resolve to any row (404 semantics)");
    }

    @Test
    @TestTransaction
    void cronograma_repository_resolves_by_presupuesto_and_hides_from_foreign_owner() {
        Seed seed = seedParentGraph();
        Usuario foreign = persistUsuario("foreign-crono-2@ex.com");
        Cronograma cronograma = persistCronograma(seed.presupuestoId);

        Optional<Cronograma> ownerResolved =
                cronogramaRepository.findByPresupuestoAndOwnerScope(cronograma.presupuestoId, seed.ownerId);
        assertTrue(ownerResolved.isPresent(), "owner must resolve cronograma by presupuestoId");

        Optional<Cronograma> foreignResolved =
                cronogramaRepository.findByPresupuestoAndOwnerScope(cronograma.presupuestoId, foreign.id);
        assertTrue(
                foreignResolved.isEmpty(),
                "foreign owner must NOT resolve cronograma by presupuestoId (404 semantics)");
    }

    // ──────────────────────────────────────────────────────────────────────
    // helpers
    // ──────────────────────────────────────────────────────────────────────

    private static Field lookupField(Class<?> entity, String name) {
        for (Class<?> current = entity; current != null; current = current.getSuperclass()) {
            try {
                return current.getDeclaredField(name);
            } catch (NoSuchFieldException ignored) {
                // keep walking up
            }
        }
        return null;
    }

    private Usuario persistUsuario(String email) {
        Usuario u = new Usuario();
        u.nombre = "Usuario " + email;
        u.email = email;
        u.passwordHash = "hash-placeholder";
        u.rol = Rol.USUARIO;
        u.emailVerificado = true;
        u.activo = true;
        u.createdAt = Instant.now();
        u.updatedAt = Instant.now();
        usuarioRepository.persist(u);
        return u;
    }

    private Cronograma persistCronograma(Long presupuestoId) {
        Cronograma cronograma = new Cronograma();
        cronograma.presupuestoId = presupuestoId;
        cronograma.unidadTiempo = "SEMANA";
        cronograma.numeroPeriodos = 12;
        cronograma.totalGeneralRevisado = null;
        cronograma.fechaRevision = null;
        cronograma.presupuestoFingerprintRevisado = null;
        cronogramaRepository.persist(cronograma);
        return cronograma;
    }

    private Seed seedParentGraph() {
        Usuario owner = persistUsuario("owner-crono@ex.com");
        Proyecto proyecto = new Proyecto();
        proyecto.usuarioId = owner.id;
        proyecto.nombreProyecto = "Cronograma Owner";
        proyecto.codigo = "P-CRONO";
        proyecto.descripcion = "Cronograma test";
        proyecto.anio = (short) 2026;
        proyecto.plazoEjecucion = (short) 6;
        proyecto.plazoUnidad = ec.uce.propuestas.proyecto.entity.PlazoUnidad.MES;
        proyecto.estado = ec.uce.propuestas.proyecto.entity.EstadoProyecto.BORRADOR;
        proyecto.direccionInstitucional = "GAD Test";
        proyecto.createdAt = Instant.now();
        proyecto.updatedAt = Instant.now();
        proyectoRepository.persist(proyecto);

        Presupuesto presupuesto = new Presupuesto();
        presupuesto.proyectoId = proyecto.id;
        presupuesto.version = (short) 1;
        presupuesto.esVigente = true;
        presupuesto.total = BigDecimal.ZERO;
        presupuesto.createdAt = Instant.now();
        presupuesto.updatedAt = Instant.now();
        presupuestoRepository.persist(presupuesto);

        return new Seed(owner.id, presupuesto.id);
    }

    private record Seed(Long ownerId, Long presupuestoId) {}
}
