-- V003__seed_insumos.sql
-- Central IESS input base (§17 #2). 93 insumos from
-- thesis-docs/plan/domain/_artifacts/insumos-seed-apus-cetro-medico-tulcan.csv.
-- Codes generated as EQ-NNN (EQUIPO), MO-NNN (MANO_OBRA), MA-NNN (MATERIAL).
-- EQUIPO and MANO_OBRA rows use unidad='h' (schema constraint).

INSERT INTO base_insumos (nombre, tipo, proyecto_id, archivada) VALUES
  ('Base IESS Cetro Médico Tulcán', 'CENTRAL', NULL, FALSE);

WITH base AS (
  SELECT id FROM base_insumos WHERE nombre = 'Base IESS Cetro Médico Tulcán'
)
INSERT INTO insumo (base_id, codigo, tipo, descripcion, unidad, precio_unitario)
SELECT base.id, v.codigo, v.tipo, v.descripcion, v.unidad, v.precio_unitario
FROM base, (VALUES
  ('MO-001', 'MANO_OBRA', 'Maestro mayor en ejecución de  obras civiles  (EO C1)', 'h', 4.75),
  ('MO-002', 'MANO_OBRA', 'Peón (EO E2)', 'h', 4.23),
  ('EQ-001', 'EQUIPO', 'Volqueta', 'h', 25.0),
  ('EQ-002', 'EQUIPO', 'Cargadora frontal', 'h', 29.65),
  ('MO-003', 'MANO_OBRA', 'Chofer: Volquetas ( EO C1) (CHOFERES PROFESIONALES)', 'h', 6.22),
  ('MO-004', 'MANO_OBRA', 'Operador cargadora frontal (Payloader sobre ruedas u orugas) (OPER-EO C1 GRUPO I)', 'h', 4.75),
  ('EQ-003', 'EQUIPO', 'Andamio', 'h', 0.1),
  ('EQ-004', 'EQUIPO', 'Cortadora eléctrica de porcelanato/cerámica', 'h', 0.75),
  ('EQ-005', 'EQUIPO', 'Amoladora', 'h', 1.17),
  ('MO-005', 'MANO_OBRA', 'Instalador de revestimiento en general  (EO D2)', 'h', 4.28),
  ('MA-001', 'MATERIAL', 'Mortero adhesivo bicomponente', 'Kg', 0.59),
  ('MA-002', 'MATERIAL', 'Emporador', 'Kg', 1.12),
  ('MA-003', 'MATERIAL', 'Agua', 'm3', 0.9),
  ('MA-004', 'MATERIAL', 'Porcelanato rectificado en pared (0.60x 0.30 m)', 'm2', 16.32),
  ('EQ-006', 'EQUIPO', 'Taladro eléctrico', 'h', 1.1),
  ('MO-006', 'MANO_OBRA', 'Carpintero  (EO D2)', 'h', 4.28),
  ('MA-005', 'MATERIAL', 'Jaladera de acero inoxidable para puerta corrediza de tablero de densidad media', 'u', 7.61),
  ('MA-006', 'MATERIAL', 'Tacos y tornillos', 'u', 0.05),
  ('MA-007', 'MATERIAL', 'Kit de accesorios para puerta corrediza tipo granero incluye rieles y rodillo,conectores de riel y pared,tapas', 'u', 97.0),
  ('MA-008', 'MATERIAL', 'Tablero de fibra de densidad media 10mm', 'm2', 21.89),
  ('MA-009', 'MATERIAL', 'Hoja de puertas en tablero de fibra de densidad media RH tamborada', 'm2', 88.54),
  ('EQ-007', 'EQUIPO', 'Sierra circular', 'h', 1.5),
  ('MO-007', 'MANO_OBRA', 'Ayudante de carpintero (EO E2)', 'h', 4.23),
  ('MA-010', 'MATERIAL', 'Pegamento blanco para madera', 'gal', 10.55),
  ('MA-011', 'MATERIAL', 'Tablero de fibra de densidad media- RH 15mm melamínico', 'm2', 22.02),
  ('MA-012', 'MATERIAL', 'Riel de deslizamiento en cajones', 'm', 3.71),
  ('MA-013', 'MATERIAL', 'Tablero contrachapado 15mm industrial', 'm2', 14.09),
  ('MA-014', 'MATERIAL', 'Sellador para superficie', 'gal', 32.5),
  ('MA-015', 'MATERIAL', 'Tornillos de madera y cubre huecos', 'u', 0.1),
  ('MA-016', 'MATERIAL', 'Niveladores de altura para mueble', 'u', 1.27),
  ('MA-017', 'MATERIAL', 'Bisagra de cazoleta', 'u', 1.34),
  ('EQ-008', 'EQUIPO', 'Soldadora oxiacetilénica', 'h', 2.0),
  ('MA-018', 'MATERIAL', 'Electrodos TIG (10 unidades 1.6x175mm)', 'Kg', 16.5),
  ('MA-019', 'MATERIAL', 'Tubo de acero inoxidable 2"x1.5mm', 'm', 8.22),
  ('MA-020', 'MATERIAL', 'Sujecciones de acero inoxidable pasamanos muro', 'u', 10.2),
  ('MO-008', 'MANO_OBRA', 'Electricista (EO D2)', 'h', 4.28),
  ('MO-009', 'MANO_OBRA', 'Ayudante de electricista (EO E2)', 'h', 4.23),
  ('MO-010', 'MANO_OBRA', 'Maestro Eléctrico/liniero/subestaciónes ( EO C1)', 'h', 4.75),
  ('MA-021', 'MATERIAL', 'Centro de Tomas para Quirófano (4 tomas dúplex  y 4 tomas tierra)', 'u', 406.0),
  ('MA-022', 'MATERIAL', 'Cinta aislante', 'u', 0.97),
  ('MA-023', 'MATERIAL', 'Centro de carga trifásico de 12 espacios', 'u', 109.73),
  ('EQ-009', 'EQUIPO', 'Escalera tipo tijera', 'h', 0.1),
  ('MA-024', 'MATERIAL', 'Cable flexible THHN Flex # 12 AWG', 'm', 0.57),
  ('MA-025', 'MATERIAL', 'Amarras de 10 cm plásticas', 'u', 0.02),
  ('MA-026', 'MATERIAL', 'Patch cord cat 6A F/UTP 3ft', 'u', 14.15),
  ('MA-027', 'MATERIAL', 'Etiqueta de identificación', 'u', 0.42),
  ('MA-028', 'MATERIAL', 'Expansores de 3/8"', 'u', 0.6),
  ('MA-029', 'MATERIAL', 'Tuercas 3/8"', 'u', 0.05),
  ('MA-030', 'MATERIAL', 'Arandelas 3/8"', 'u', 0.05),
  ('MA-031', 'MATERIAL', 'Varilla roscada galvanizada 3/8"', 'm', 1.69),
  ('MA-032', 'MATERIAL', 'Sujetador de bandeja 1/4 lamina galvanizada', 'u', 0.15),
  ('MA-033', 'MATERIAL', 'Canal estructural troquelado 1 5/8"de ancho x 1 5/8" de alto', 'm', 4.93),
  ('EQ-010', 'EQUIPO', 'Martillo neumático rompedor', 'h', 6.8),
  ('EQ-011', 'EQUIPO', 'Cortadora de hormigón', 'h', 1.28),
  ('MO-011', 'MANO_OBRA', 'Operador de equipo liviano (EO D2)', 'h', 4.28),
  ('MA-034', 'MATERIAL', 'Aditivo ligante con base a látex', 'Kg', 6.75),
  ('MA-035', 'MATERIAL', 'Cemento portland', 'Kg', 0.16),
  ('MA-036', 'MATERIAL', 'Arena puesta en obra', 'm3', 12.5),
  ('MO-012', 'MANO_OBRA', 'Plomero  (EO D2)', 'h', 4.28),
  ('MO-013', 'MANO_OBRA', 'Ayudante de plomero (EO E2)', 'h', 4.23),
  ('MA-037', 'MATERIAL', 'Válvula de compuerta de bronce 3/4" o 19mm', 'u', 20.21),
  ('MA-038', 'MATERIAL', 'Cinta para uniones roscadas', 'rollo', 0.97),
  ('MA-039', 'MATERIAL', 'Sellante', 'u', 3.64),
  ('MO-014', 'MANO_OBRA', 'Inspector de obra (EO B3)', 'h', 4.76),
  ('MO-015', 'MANO_OBRA', 'Técnico Electromecánico  de construcción (EO D2)', 'h', 4.28),
  ('MA-040', 'MATERIAL', 'Base metálica para ventilador,incluye soporte y varilla roscada', 'u', 35.0),
  ('MA-041', 'MATERIAL', 'Tablero de control ventilador ON/OFF, manual y automático, programación diaria y semanal', 'u', 214.94),
  ('MA-042', 'MATERIAL', 'Perno galvanizado camisa larga 5/16 x 1 1/2"', 'u', 0.26),
  ('MA-043', 'MATERIAL', 'Manguera metálica anillada con recubrimiento de PVC Ø= ¾”.', 'm', 1.95),
  ('MA-044', 'MATERIAL', 'Filtro MERV 4', 'u', 58.64),
  ('MA-045', 'MATERIAL', 'Ventilador centrífugo de Extracción In Line de Acople Directo 660cfm@1,32swp; incluye motor', 'u', 917.86),
  ('MO-016', 'MANO_OBRA', 'Hojalatero (EO D2)', 'h', 4.28),
  ('MA-046', 'MATERIAL', 'Rejilla de puerta 16"x8"; blanca/aluminio; aletas fijas', 'u', 40.6),
  ('MA-047', 'MATERIAL', 'Tornillo autoroscante 1 1/4"x6mm', 'u', 0.03),
  ('MA-048', 'MATERIAL', 'Consola vertical de aleación de aluminio 6063; incluye 3 gases + 4 TE N +4TE R y accesorios', 'u', 2154.24),
  ('MA-049', 'MATERIAL', 'Suelda de plata al 15%', 'varilla', 8.5),
  ('MA-050', 'MATERIAL', 'Nitrógeno seco.', 'm3', 7.89),
  ('MA-051', 'MATERIAL', 'Unión EMT 3/4"', 'u', 0.65),
  ('MA-052', 'MATERIAL', 'Conector EMT 3/4"', 'u', 0.53),
  ('MA-053', 'MATERIAL', 'Tubo EMT 3/4"', 'u', 5.98),
  ('MA-054', 'MATERIAL', 'Abrazadera EMT 3/4"', 'u', 0.1),
  ('MA-055', 'MATERIAL', 'Pintura poliuretano', 'gal', 54.29),
  ('MA-056', 'MATERIAL', 'Caja cuadrada de paso 10x10cm', 'u', 1.33),
  ('MA-057', 'MATERIAL', 'Tapa metálica cuadrada 10 x 10', 'u', 0.39),
  ('MA-058', 'MATERIAL', 'Alambre galvanizado #18', 'Kg', 2.1),
  ('MA-059', 'MATERIAL', 'Fundas resistentes de color rojo', 'u', 0.3),
  ('MA-060', 'MATERIAL', 'Guantes de cuero', 'u', 3.84),
  ('MA-061', 'MATERIAL', 'Gafas de protección', 'u', 3.77),
  ('MA-062', 'MATERIAL', 'Mascarilla de protección', 'u', 2.6),
  ('MA-063', 'MATERIAL', 'Aserrín', 'Kg', 1.0),
  ('MA-064', 'MATERIAL', 'Pala', 'u', 12.99),
  ('MA-065', 'MATERIAL', 'Escobilla', 'u', 4.01),
  ('MA-066', 'MATERIAL', 'Overol', 'u', 33.99)
) AS v(codigo, tipo, descripcion, unidad, precio_unitario);
